services:
  app-blue:
    container_name: fit-blue
    image: ${DOCKER_USERNAME}/fit-be:latest
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - blue/.env.blue
    environment:
      - APP_PORT=3000
      - REDIS_HOST=redis-blue
      - REDIS_PORT=6379
      - NODE_ENV=production
      - ENV_FILE=.env.blue
      - DB_HOST=postgres-blue
    networks:
      - redis-network
    depends_on:
      - redis-blue
      - postgres-blue

  app-green:
    container_name: fit-green
    image: ${DOCKER_USERNAME}/fit-be:latest
    restart: unless-stopped
    ports:
      - '3001:3000'
    env_file:
      - green/.env.green
    environment:
      - APP_PORT=3001
      - REDIS_HOST=redis-green
      - REDIS_PORT=6379
      - NODE_ENV=production
      - ENV_FILE=.env.green
      - DB_HOST=postgres-green
    networks:
      - redis-network
    depends_on:
      - redis-green
      - postgres-green

  redis-blue:
    container_name: redis-blue
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - redis-network
    restart: unless-stopped

  redis-green:
    container_name: redis-green
    image: redis:latest
    ports:
      - '6380:6379'
    networks:
      - redis-network
    restart: unless-stopped

  postgres-blue:
    container_name: postgres-blue
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_blue_data:/var/lib/postgresql/data
    networks:
      - redis-network

  postgres-green:
    container_name: postgres-green
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5433:5432'
    volumes:
      - postgres_green_data:/var/lib/postgresql/data
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  postgres_blue_data:
  postgres_green_data:
