services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - redis-network
    restart: unless-stopped
    depends_on:
      - app-blue
      - app-green
    
  app-blue:
    container_name: fit-blue
    image: ${DOCKER_USERNAME}/fit-be:latest
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - blue/.env.blue
    environment:
      - APP_PORT=3000
      - REDIS_HOST=redis-blue
      - REDIS_PORT=6379
      - NODE_ENV=production
      - ENV_FILE=.env.blue
      - DB_HOST=postgres
      - DB_PORT=5432
    networks:
      - redis-network
    depends_on:
      redis-blue:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  app-green:
    container_name: fit-green
    image: ${DOCKER_USERNAME}/fit-be:latest
    restart: unless-stopped
    ports:
      - '3001:3000'
    env_file:
      - green/.env.green
    environment:
      - APP_PORT=3001
      - REDIS_HOST=redis-green
      - REDIS_PORT=6379
      - NODE_ENV=production
      - ENV_FILE=.env.green
      - DB_HOST=postgres
      - DB_PORT=5432
    networks:
      - redis-network
    depends_on:
      redis-green:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis-blue:
    container_name: redis-blue
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - redis-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis-green:
    container_name: redis-green
    image: redis:latest
    ports:
      - '6380:6379'
    networks:
      - redis-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=fit
    networks:
      - redis-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d fit"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  redis-network:
    driver: bridge

volumes:
  postgres-data:
